################################################################################
# 配置参考
# - https://github.com/Infatuation-Fei/rule/blob/main/Stash/配置模板/Config-Stash.yaml
# 规则参考
# - https://github.com/DivineEngine/Profiles/tree/master/Clash/RuleSet
################################################################################
# autocorrect-disable

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

http:
  mitm:
    - g.cn
    - "*.google.cn"
    - "www.firefox.com.cn"
    - sub.store
  script:
    - match: ^https?:\/\/sub\.store
      name: sub-store
      type: request
      require-body: true
      timeout: 120
  rewrite:
    - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
    - ^https?:\/\/(www.)?firefox\.com\.cn\/(download\/)?$ https://www.mozilla.org/zh-CN/firefox/new/ 302
script-providers:
  sub-store:
    url: https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/backend/sub-store.min.js
    interval: 86400

# 假如用组合订阅多个机场，就没必要使用 subscribe-url 了
subscribe-url: https://sub.store/download/collection/subs
# 替换上面文字用于Stash获取机场流量信息并在主页显示(Stash1.6.1 build287+支持)

# 远程资源默认配置
remote-resources-default-config: &rrdc
  type: http
  interval: 86400

proxy-providers:
  # 全部节点
  All: &All # 建立锚点
    <<: *rrdc
    # 此处默认使用 sub-store 订阅链接，如果需要使用其他订阅链接，可以替换下面的 url 即可
    url: "https://sub.store/download/collection/subs"
    # 可以使用任意类型的链接仅替换上面文字，多个链接使用英文符号的竖杠|隔开一起写上即可；
    # Sub-Store 与 Clash 类型订阅链接替换掉整个引号""内的链接
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  # 美国节点
  US:
    <<: *All # 引用锚点内容
    filter: 美|🇺🇲|US|(?i)States|American

  # 香港节点
  HK:
    <<: *All
    filter: 港|🇭🇰|HK|(?i)Hong

  # 日本节点
  JP:
    <<: *All
    filter: 日|🇯🇵|东京|JP|(?i)Japan

  # 台湾节点
  TW:
    <<: *All
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan


proxies:

proxy-groups:

  - name: SSID Auto Mode
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/SSID.png
    proxies:
    # 此处为配置文件中的已有策略组
      - Server Strategy
      - DIRECT  # 虽说 DIRECT 是保留字。但必须配置该策略选项，于此代理集的 proxies 下，不然该代理集就只有 1 个策略选项
    ssid-policy:
    # cellular: 保留字，指代蜂窝数据条件下
    # default：保留字，指代其他 SSID 条件下，默认为 DIRECT 策略
    # DIRECT：保留字，直连策略
      HedyLamarr: DIRECT  # HedyLamarr，为 SSID 名称
      cellular: Server Strategy
      default: Server Strategy

  - name: Server Strategy
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
    proxies:
      - Auto Select
      - Manual Select
      - Fallback

  - name: Manual Select
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All

  - name: Global Proxy
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    proxies: &GP
      - SSID Auto Mode
      - DIRECT
      - Hong Kong
      - Japan
      - America
      - Tai Wan

  - name: Global Direct
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png
    proxies: &GD
      - DIRECT
      - SSID Auto Mode

  - name: Final
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      - SSID Auto Mode
      - DIRECT

  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    proxies:
      *GP

  - name: Twitter
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
    proxies:
      *GP

  - name: Apple
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
    proxies:
      *GD

  - name: Microsoft
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
    proxies:
      *GD

  - name: Game
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
    proxies:
      *GP

  - name: AD Block
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png
    proxies:
      - REJECT

  - name: Auto Select
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    use:
      - All

  - name: Fallback
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bypass.png
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - All

  - name: Hong Kong
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - HK

  - name: Japan
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - JP

  - name: Tai Wan
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png
    use:
      - TW

  - name: America
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - US



rule-providers:

  Global Direct:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Direct/Direct.yaml?raw=true"
    path: ./ruleset/global-direct.yaml


  AD Block:
    <<: *rrdc
    behavior: domain-text
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.txt?raw=true"
    path: ./ruleset/ad-block.yaml


  Telegram:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Telegram/Telegram.yaml?raw=true"
    path: ./ruleset/telegram.yaml


  Twitter:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Twitter/Twitter.yaml?raw=true"
    path: ./ruleset/twitter.yaml


  Apple:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Apple/Apple.yaml?raw=true"
    path: ./ruleset/apple.yaml


  Microsoft:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Microsoft/Microsoft.yaml?raw=true"
    path: ./ruleset/microsoft.yaml

  Game:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Game/Game.yaml?raw=true"
    path: ./ruleset/game.yaml


  China:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/China/China.yaml?raw=true"
    path: ./ruleset/china.yaml


  China IPs:
    <<: *rrdc
    behavior: ipcidr-text
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.txt?raw=true"
    path: ./ruleset/china-ips.yaml

  Global Proxy:
    <<: *rrdc
    behavior: domain-text
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Proxy/Proxy_Domain.txt?raw=true"
    path: ./ruleset/global-proxy.yaml

  Lan:
    <<: *rrdc
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Lan/Lan.yaml?raw=true"
    path: ./ruleset/lan.yaml


rules:
  - RULE-SET,Global Direct,Global Direct
  - RULE-SET,AD Block,AD Block
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Twitter,Twitter
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Game,Game
  - RULE-SET,Global Proxy,Global Proxy
  - RULE-SET,China,Global Direct
  - RULE-SET,China IPs,Global Direct
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,Global Direct
  - MATCH,Final