################################################################################
# 配置参考
# - https://github.com/Infatuation-Fei/rule/blob/main/Stash/配置模板/Config-Stash.yaml
# 规则参考
# - https://github.com/DivineEngine/Profiles/tree/master/Clash/RuleSet
################################################################################
# autocorrect-disable
# 将proxy-providers里面链接中的“你的订阅链接”替换即可

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

# 假如用组合订阅多个机场，就没必要使用 subscribe-url 了
subscribe-url: https://sub.store/download/collection/subs
#替换上面文字用于Stash获取机场流量信息并在主页显示(Stash1.6.1 build287+支持)

proxy-providers:
  #全部节点
  All: &All #建立锚点
    type: http
    # 此处默认使用 sub-store 订阅链接，如果需要使用其他订阅链接，可以替换下面的 url 即可
    url: "https://sub.store/download/collection/subs"
    # 可以使用任意类型的链接仅替换上面文字，多个链接使用英文符号的竖杠|隔开一起写上即可；
    # Sub-Store 与 Clash 类型订阅链接替换掉整个引号""内的链接
    interval: 86400
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #美国节点
  US:
    <<: *All #引用锚点内容
    filter: 美|🇺🇲|US|(?i)States|American

  #香港节点
  HK:
    <<: *All
    filter: 港|🇭🇰|HK|(?i)Hong

  #日本节点
  JP:
    <<: *All
    filter: 日|🇯🇵|东京|JP|(?i)Japan

  #台湾节点
  TW:
    <<: *All
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies:

proxy-groups:

  - name: SSID Auto Mode
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/SSID.png
    proxies:
    # 此处为配置文件中的已有策略组
      - 节点选择
      - DIRECT  # 虽说 DIRECT 是保留字。但必须配置该策略选项，于此代理集的 proxies 下，不然该代理集就只有 1 个策略选项
    ssid-policy:
    # cellular: 保留字，指代蜂窝数据条件下
    # default：保留字，指代其他 SSID 条件下，默认为 DIRECT 策略
    # DIRECT：保留字，直连策略
      HedyLamarr: DIRECT  # HedyLamarr，为 SSID 名称
      cellular: 节点选择
      default: 节点选择

  - name: 节点选择
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
    proxies:
      - 自动选择
      - 手动切换
      - 故障转移

  - name: 手动切换
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All

  - name: 自动选择
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    use:
       - All

  - name: 故障转移
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bypass.png
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
       - All

  - name: Global Proxy
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    proxies: &G
      - SSID Auto Mode
      - DIRECT
      - 香港节点
      - 日本节点
      - 美国节点
      - 台湾节点

  - name: Global Direct
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png
    proxies: &C
      - DIRECT
      - SSID Auto Mode

  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    proxies:
      *G

  - name: Twitter
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
    proxies:
      *G



  - name: Apple
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
    proxies:
      *C

  - name: Microsoft
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
    proxies:
      *C

  - name: Game
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
    proxies:
      *G

  - name: AD Block
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png
    proxies:
      - REJECT

  - name: 漏网之鱼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      *G

  - name: 香港节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - HK

  - name: 日本节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - JP

  - name: 台湾节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png
    use:
      - TW

  - name: 美国节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - US

rule-providers:

  Global Direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml"
    path: ./ruleset/direct.yaml
    interval: 86400

  AD Block:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml"
    path: ./ruleset/AdDomain.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400

  Twitter:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
    path: ./ruleset/Twitter.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global Proxy:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/Global-Domain.yaml
    interval: 86400

  Lan:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/lan.yaml
    interval: 86400

rules:
  - RULE-SET,Global Direct,Global Direct
  - RULE-SET,AD Block,AD Block
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Twitter,Twitter
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Game,Game
  - RULE-SET,Global Proxy,Global Proxy
  - RULE-SET,China,Global Direct
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,Global Direct
  - MATCH,漏网之鱼